### ISSUE TITLE
Click on info icon -> Lightbox with html page in an iframe

### ISSUE THREAD

**Issue by MartinSchott** [ASKnetCommunity/Training#10]
B_men wrote in old issue: 

When a user clicks on the info icon, a lightbox opens and the website of that module or resource is displayed in an iframe.

**Comment by timmwille** [comment]
has issue as in #22

**Comment by MartinSchott** [comment]
I think we should (for now!) do it another way: to link the info icon to the URL of the module (similar to the "manual" button in resources)

(like mentioned in this issue https://github.com/ASKnetCommunity/Training/issues/26 )
