### ISSUE TITLE
Time and Day break function breaks again compared between fix branches

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#101]
@saisilinus during the final review I noticed, that between the last merges there must have been a change in code that interferes with the fix initiated to the time and day break function in the beginning.

If I compare the first branch I merged (also including all other bug fixes and time durations etc.) it still works, so it must have happened with the authors or the trainers note feature branch. 

I traced this code snipped down but I'm not sure if this is causing it as it might be a double feature together with the other solution you found?
https://github.com/ASKnetCommunity/Training/blob/527bf03f95ce6bc459aa43d4897b9e20114eff61/assets/js/index.js#L158
https://github.com/ASKnetCommunity/Training/blob/527bf03f95ce6bc459aa43d4897b9e20114eff61/assets/js/index.js#L660
https://github.com/ASKnetCommunity/Training/blob/527bf03f95ce6bc459aa43d4897b9e20114eff61/assets/js/index.js#L771

I understand the time edit function has to be loaded in the beginning at least, after that the following things I noticed that need some care:

- [x] 1. The edit function does not work anymore as I can hit "edit" and enter a time etc. but the save button won't react anymore
- [x] 2. The title set as a "standard" one can see when no editing is done will disappear and show an empty bar when the time was edited, so it does not load the default set title for time or day break (I think this is actually also in the original fix branch the case, so not sure what code snipped might be missing to load the default if nothing in the title was changed)

**Comment by bmen** [comment]
Looks like it's working. Good work @saisilinus
