### ISSUE TITLE
show proper time preview if module is empty or time is 0

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#110]
is related to #105

**Comment by saisilinus** [comment]
I need more guidance on this. What do you want to show when the time is 0 or the module is empty?

**Comment by timmwille** [comment]
![grafik](https://github.com/ASKnetCommunity/Training/assets/8081055/0a352f01-f252-4b27-9746-9f060c415309)

**Comment by timmwille** [comment]
done
