### ISSUE TITLE
edit the Training Title and description when changes are needed

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#113]
first edit works, then the edit function dissapears

**Comment by walthierer** [comment]
i´m not sure if was is already part of the fix, but also the save button in the edit title-pop-up-window, doesnt close the pop-up window. e.g. if i "add trainer notes" in the pop-up window i click on save and the window disapears, this is not working for the edit the title pop-up window. i hope its clear what i mean :)) if not, i will add further explanations. 

<img width="370" alt="Bildschirmfoto 2023-11-14 um 14 43 32" src="https://github.com/ASKnetCommunity/Training/assets/64423638/41415609-f3d2-423c-9974-303ea938f33f">

**Comment by saisilinus** [comment]
I think this has already been fixed in #117. Please check and revert @walthierer
