### ISSUE TITLE
Give Reference in the print view for the TRAINING ASKnet identity

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#114]

**Comment by timmwille** [comment]
![grafik](https://github.com/ASKnetCommunity/Training/assets/8081055/3a41e977-8f32-44d4-b736-48095f53930a)

- might need a fix anyway with the edit button? @saisilinus can you help with this?


here there is space:

![grafik](https://github.com/ASKnetCommunity/Training/assets/8081055/8ca6256e-17b8-4010-886d-b979e09bc029)


the edit button can move down?

**Comment by walthierer** [comment]
i created 2 versions the only difference is the placement of the button (i think i like it more in the middle)
the proposal has more space for the description and the title. i divided the space inside the orange box (orange outline) again into 4 columns. both, title and description, got 3 of them. 
the beloved clipboard icon had to go :(( it looked strange with the ASKnet logo. 

i will attach a screeshot with the reference lines and the green boxes (multiples of 4)

![planner_header_1](https://github.com/ASKnetCommunity/Training/assets/64423638/9f732bf1-e238-4f93-913f-3a590e1ce3d7)
  
<img width="1079" alt="Bildschirmfoto 2023-12-01 um 18 32 18" src="https://github.com/ASKnetCommunity/Training/assets/64423638/da5cbffb-7434-4fce-82b4-d2b0b0540059">


![planner_header_2](https://github.com/ASKnetCommunity/Training/assets/64423638/8aa58242-72c7-48d8-b4ab-d2979976ead8)

**Comment by timmwille** [comment]
thx @walthierer I hope you can work with this @bmen 

Is related to #59
