### ISSUE TITLE
Create and improve single page for a module

### ISSUE THREAD

**Issue by bmen** [ASKnetCommunity/Training#140]

**Comment by timmwille** [comment]
Actually I think the tooltip should still display `details` or `info` still when you hover over the info icon @bmen ;)

**Comment by timmwille** [comment]
- [ ] would be great to have the option to visit the single page from all module views also at the #10 level and have the option there to go back into the overview page! @bmen

**Comment by walthierer** [comment]
[ ] The single page for a module looks a "bit lost" (screenshot). A structure like 

**Module: Title of the Module**

clarifies what is shown. --> the word Module should be added
(from the meeting / presentation on 13.12.23)

<img width="1321" alt="Bildschirmfoto 2023-12-15 um 09 44 46" src="https://github.com/ASKnetCommunity/Training/assets/64423638/8523b78e-f2a2-4ace-95d0-f919c2cbc88b">

**Comment by timmwille** [comment]
@bmen some tasks in the comments are still open, can you check and either work on for release 1.2 or create a good task description on top for @saisilinus to work with!?
