### ISSUE TITLE
provide option to preselect modules via dynamic link (e.g. to share or on a button of overview page)

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#143]
- Option 1: this will add a module via dynamic link straight to the planning section
- Option 2: this will add a search pre-filter via `/?search="<search input>"` e.g. as dynamic link to send/embed 

@saisilinus @bmen can you check if this is possible via Jekyll?

**Comment by bmen** [comment]
This would not be an issue for Jekyll, but for Javascript, as these links are dynamic while the user creates the plan.
Do you have any ideas? @saisilinus

**Comment by saisilinus** [comment]
Yes. Its a JavaScript issue. We have to store the data somewhere as we navigate between the pages. We can use the query params for storage and populate the training plan schedule and/or the search input whenever one loads the page.
