### ISSUE TITLE
Module Introduction Duration - Correct Abbreviation for Minutes --> min and a space between number and Abbreviation

### ISSUE THREAD

**Issue by walthierer** [ASKnetCommunity/Training#145]
the correct way would be "**2 min**" instead of "2m", thanks for changing :)
<img width="224" alt="Bildschirmfoto 2023-11-28 um 12 04 21" src="https://github.com/ASKnetCommunity/Training/assets/64423638/4171f9fb-2c93-45f4-b46e-0215b91a0fb8">

**Comment by saisilinus** [comment]
![image](https://github.com/ASKnetCommunity/Training/assets/42277372/1be8b62d-625a-4581-a149-70936aad7521)

Like this ☝🏿 @walthierer? Or like this 👇🏿 ?

![image](https://github.com/ASKnetCommunity/Training/assets/42277372/ffa017d8-a8f8-45f4-9be4-c4b32e4acb23)

**Comment by walthierer** [comment]
:DD im checking it since 3 min but i don't see any difference hahaha but i know what you mean "1 hours 55 minutes" vs. "1 h 55 min"
good questions, usually i would go for the hours and minutes version, BUT i´m not sure if and if yes, how the module section will be displayed in future versions. I think the "xx h xx min" variant needs less space and is therefore easier to display / design / manage, etc.

**Comment by walthierer** [comment]
or do you mean the space after 1? like "1h" vs "1 h"? then i would go for the second version with the space, because its the same with the min

**Comment by saisilinus** [comment]
I've added the fix to #144
