### ISSUE TITLE
Improvemts to the Main Planner Area

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#150]
connected to print view and will solve
- [x] #59 
- [x] #114 
- [x] in parts #149 
- [x] linked to the left panel improvements #133

**Comment by walthierer** [comment]
following issues should be added here:
- [ ] #161 
- [ ] #162

**Comment by timmwille** [comment]
> following issues should be added here:
> 
>     * [ ]  [Removal of features with no function / "promising" hints  #161](https://github.com/ASKnetCommunity/Training/issues/161)
> 
>     * [ ]  [New icon for removing modules from the training configurator #162](https://github.com/ASKnetCommunity/Training/issues/162)

not sure what the alternative icon would be though

**Comment by timmwille** [comment]
from @walthierer  my preferd structure would be: 

Module in Main area as listed:

1. larger titel on top
2. image
3. learning objective
4. add trainer notes (content related to learning obj.)
5. single row with: time, difficulty level, max. participants, min. trainer, costs
6. single row with: licence (Timm: or below the learning objectives, next to the trainer notes button)
7. Introduction time slot


then the attached resources follow
1. title
2. description
3. add trainer notes 
4. single row with: time, level of difficulty, cost
5. single row with: licence, author(s)
