### ISSUE TITLE
New icon for removing modules from the training configurator

### ISSUE THREAD

**Issue by walthierer** [ASKnetCommunity/Training#162]
the icon for "deleting" (bin - icon) could be miss leading for some users. the icon gives the false impression of "deleting" in fact the module isn´t deleted, its just removed from the training plan and goes back to the module list on the left side. A new icon has to be found. 

<img width="861" alt="Bildschirmfoto 2023-12-15 um 10 27 18" src="https://github.com/ASKnetCommunity/Training/assets/64423638/77e5e44b-1709-4d38-b7de-f874979bea5b">

edit:
- [x] change to https://fontawesome.com/icons/circle-xmark?f=classic&s=solid

**Comment by timmwille** [comment]
that is a funny one, I think it is ok for now but in case there is a better idea that will help or an animation that shows how this is moving back to the end of the module list on the left panel? What is an Icon on "remove" instead "delete"? @bmen ideas?

**Comment by bmen** [comment]
I think this is PRIO 9 or something like that

**Comment by walthierer** [comment]
dosent matter who thinks that :DD it was some user feedback we got and the thought behind it is not wrong. i think a "x" is maybe less "deleting" than a trash can and i think it is also understood by most users. 

anyways i dont see any other options than a trash can or a x, so we change the icon to x or we keep the bin..

**Comment by saisilinus** [comment]
What about a `-`?

**Comment by walthierer** [comment]
i personally think a `-` is not very common and therefore more confusing. 
i think the fact, that the module is at the end of the list, after removing and the trash can icon led to the conclusion that it means deleting. but its something user will learn fast, so this discussion is already bigger than the flaw :DD

**Comment by bmen** [comment]
There are always many opinions. You won't make everyone happy.

What is with this? https://fontawesome.com/icons/circle-xmark?f=classic&s=solid

**Comment by timmwille** [comment]
> There are always many opinions. You won't make everyone happy.
> 
> What is with this? https://fontawesome.com/icons/circle-xmark?f=classic&s=solid

yes perfect, thx!!
