### ISSUE TITLE
Tag filters have no effect in the training plan

### ISSUE THREAD

**Issue by bmen** [ASKnetCommunity/Training#163]

**Comment by saisilinus** [comment]
Please elaborate @bmen

**Comment by saisilinus** [comment]
Any issues with the filter should have been solved by #160

**Comment by bmen** [comment]
Strange, when I try the tag filter directly in the development branch, it works. If I switch to my 156-time-slots-day-breaks-in-print-view branch, it no longer works. Although I have merged this before.

Ignore the ticket for now. Leave it open as a reminder so that we can check it again when we publish the release.

**Comment by saisilinus** [comment]
No worries. Initially, there was a bug but I didn't notice it till I was working on #160 so fixed it on that PR. Your branch #156 must have been created before I added the fix. Sorry for the mixup.

**Comment by bmen** [comment]
The console gives the following error:

Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at updateSelectableModulesList (trainingsplan.js:1035:25)
    at HTMLLIElement.updateWordcloudFilter (trainingsplan.js:982:5)
