### ISSUE TITLE
Remove all links to the module detail page

### ISSUE THREAD

**Issue by bmen** [ASKnetCommunity/Training#166]
In the training plan, you can click on the headline or image of a module to go to the module details page. However, if you return to the training plan using the browser's back button, the training plan is empty and you start again from the beginning.

So all links in

- [ ] headings (sidebar)
- [ ] headings (training plan)
- [ ] Images 

of a module must be removed.

**Comment by timmwille** [comment]
Or open in a new page

**Comment by timmwille** [comment]
@saisilinus I think removing is the right move, should be later implemented in the iFrame similar to #168 would work too
