### ISSUE TITLE
Adapt and improve module and resource templates to all new changes

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#174]
All comments need a bit of double check and improvements and in existing modules/resource we can remove old comments

**Comment by walthierer** [comment]
i already updatet both, the module and resource, templates with changes to solve problems, which occurred during developing my recent OERs. Not sure if my changes covered everything.

The changes I made can be found [here in this branch](https://github.com/ASKnetCommunity/Training/tree/new_oers_by_basti)
