### ISSUE TITLE
Social Preview image and text for Overview/Startpage

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#176]
https://training.asknet.community is currently not anymore show a preview when shared on social media.

@bmen can you write a description of what would need to be done/places where?

- Title, Subtitle "**#ASKtraining** - create your custom training plan" [1]
- Image (Screenshot of startpage)

![grafik](https://github.com/ASKnetCommunity/Training/assets/8081055/dc9c59ab-51df-4e7c-a493-e645696fa546)

[1]  "**#ASKtraining** - create your custom #ASKnet training plan" might be better to link it to the context or is the URL enough?

**Comment by bmen** [comment]
ok has been implemented. There are fallbacks in the description and preview images. If no image has been defined for the page or module, the screenshot.png file is used.
