### ISSUE TITLE
Training planner - Edit Titel and description: editable only one time

### ISSUE THREAD

**Issue by walthierer** [ASKnetCommunity/Training#197]
Once the title and description text of a training is added it cant be changed. the edit button isnt clickable anymore after the first time text is added.

<img width="765" alt="Bildschirmfoto 2024-01-23 um 13 07 49" src="https://github.com/ASKnetCommunity/Training/assets/64423638/930d7d6a-7e6e-4083-ad63-dd06ca1cc2c4">

**Comment by walthierer** [comment]
i just found out, that it is also not possible to close the pop up window with the "x" button in the right upper corner

**Comment by walthierer** [comment]
another finding: its the same thing with the "edit summary notes", i only can edit them once.

![Uploading Bildschirmfoto 2024-01-24 um 11.44.42.png…]()

**Comment by saisilinus** [comment]
I've just fixed the issues you opened with #200. Please check and revert

**Comment by walthierer** [comment]
thx Linus, you are so fast :)
