### ISSUE TITLE
titel searchbar - Search module by name: update the title!

### ISSUE THREAD

**Issue by walthierer** [ASKnetCommunity/Training#198]
the searchbar doenst search by name / title it also searches throug the discriptions. the recent title indicates to me that the modules will be seachred by their name. 
The title of the searchbar should be changed, maybe to: __Search modules__

<img width="361" alt="searchbar" src="https://github.com/ASKnetCommunity/Training/assets/64423638/2c483c4f-3fde-4e3e-a99b-81dcf8a34fc1">

**Comment by saisilinus** [comment]
This should be fixed by #200
