### ISSUE TITLE
Module page iframe - Overview / back button

### ISSUE THREAD

**Issue by walthierer** [ASKnetCommunity/Training#199]
The newly created back button ("<-- Overview") from the module page also appears in the module page iframe (at the trainings planner) There it doesn't closes the iframe, instead it brings you back to the overview page displayed into the iframe.

this "<-- Overview" - button, should only appear at the module page (overview page).

<img width="1009" alt="Bildschirmfoto 2024-01-23 um 15 06 01" src="https://github.com/ASKnetCommunity/Training/assets/64423638/0a806ae2-a196-494f-99a6-ab1cf1ae20ea">

<img width="996" alt="Bildschirmfoto 2024-01-23 um 15 06 09" src="https://github.com/ASKnetCommunity/Training/assets/64423638/adce3f43-b4e2-414d-a395-40755a5d14b0">

**Comment by saisilinus** [comment]
This should be fixed by #200
