### ISSUE TITLE
critical bug: Margin too small / Padding to big for main content section

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#22]
![grafik](https://user-images.githubusercontent.com/8081055/146440922-c33ac892-c811-4eab-a28b-65ef9594bb27.png)

via `<div id="content">`

## Problem

this way via small screens or reduced windows the modules can not be dragged over or the filters are partly overlapped and can not be clicked!

**Comment by bmen** [comment]
The content area overlaps the sidebar. Solution: z-index
