### ISSUE TITLE
modules have a URL and a button/link for the URL

### ISSUE THREAD

**Issue by MartinSchott** [ASKnetCommunity/Training#26]
like each resource can have a URL which links e.g. to a wikifab article etc.

if no URL, no button/link will be shown

**Comment by MartinSchott** [comment]
added this new button 
![grafik](https://user-images.githubusercontent.com/8080649/153279821-f614ca90-2919-48e0-a6b0-31f347f24174.png)

which links to the url specified in the module yaml file (I added "url: " in all of them). Button not shown if url is empty

**Comment by bmen** [comment]
maybe you can give the manual button a more simple style (black/white) to separate from resources

**Comment by bmen** [comment]
and the name of the Button "source"

**Comment by timmwille** [comment]
Implemented for now but not yet in use, so can be closed for now
