### ISSUE TITLE
make all inactive parts of the configurator grey 

### ISSUE THREAD

**Issue by MartinSchott** [ASKnetCommunity/Training#3]
for example these here:
![grafik](https://user-images.githubusercontent.com/8080649/146061167-28ec2d98-c0cb-407c-b455-04474e64ced1.png)

with a message like "these features are not yet active"

**Comment by timmwille** [comment]
thx for the quick fix @MartinSchott

**Comment by MartinSchott** [comment]
I think the overlay was done by Basti
