### ISSUE TITLE
Print view improvement

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#59]
I think there are a few improvements for the print view:

- [ ] print view: first page with image/Table of Content/Moduls
- [x] print view: remove "Download/Save/Print" icons/buttons
- [x] print view: make sure resources costs list is on one page if possible, maybe on a separate single page even
- [ ] print view: page numbering (optional)
- [ ] print view: make sure the attachments will be put as single pages later
- [ ] fix: #156 
- [ ] connected to #150

**Comment by walthierer** [comment]
i created 2 versions the only difference is the placement of the button (i think i prefer the middle one)
the proposal has more space for the description and the title. i divided the space inside the orange box (orange outline) again into 4 columns. both, title and description, got 3 of them.
the beloved clipboard icon had to go :(( it looked strange with the ASKnet logo.

i will attach a screeshot with the reference lines and the green boxes (multiples of 4)

![planner_header_1](https://github.com/ASKnetCommunity/Training/assets/64423638/7a00b3a4-b77c-48cf-b4cf-b0d6f80dfaa3)

![planner_header_2](https://github.com/ASKnetCommunity/Training/assets/64423638/abba1e41-2138-46d1-8aa8-9657a7cc7f8b)

![grafik](https://github.com/ASKnetCommunity/Training/assets/64423638/cd5d5aab-2ead-4fb6-a26a-8b609181b10c)
