### ISSUE TITLE
Create field for "authors" 

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#70]
This would help to list a author field per resource (Person, Organisation) or add a link to reference to the owner of the document/OER

**Comment by timmwille** [comment]
it would be nice to show this field next to the "license" showing in the resource

**Comment by saisilinus** [comment]
Do you have a list of the resources and their authors @timmwille ? If so, could you please share?

**Comment by saisilinus** [comment]
I'd like to know how you intend to style the author's field. Most of the resources have multiple authors
