### ISSUE TITLE
 if a resource has duration of 0 minutes, don't show minutes at all on the description/right of the resource

### ISSUE THREAD

**Issue by MartinSchott** [ASKnetCommunity/Training#8]

**Comment by MartinSchott** [comment]
MaxHoffmann wrote in the old issue: 
if duration 0 -> no clocktime shown

**Comment by yara89** [comment]
@timmwille  I might need some more context and clarification for the configurator and tasks and issues and so on I could contribute, I am not sure which duration you mean,  is it possible for some overview of the flow of work, and tasks/issues for the sites worked on, so I could see where I could play a role and support

**Comment by MartinSchott** [comment]
task: if 0 minutes, don't show minutes at all
