### ISSUE TITLE
costs for sanitary pads resource

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#87]
@dawaedina27 can you provide that info?

**Comment by dawaedina27** [comment]
I have estimated it to be $1500

**Comment by timmwille** [comment]
@dawaedina27 can you check again: 1 Resource/Item Material cost (not the cost for the whole Training) 

I would have thought material for one pad does not cost much more than 2-5$ max?  

Depending on all participants that quantity can be increased in the training planner but not to calculate the fees, rent and other cost for the training itself that is a bit too much to calculate in and can be very different in some cases.

**Comment by dawaedina27** [comment]
oh! I thought it was for the whole activity (training) 
Let it be $105 since the participants were 30 with an estimation of making a piece at $3.5 ($105 can make 30 pieces of sanitary pads)
