### ISSUE TITLE
We may want to rename "Time Break" into "Time Slot" as this adds extra minutes to a Module 

### ISSUE THREAD

**Issue by timmwille** [ASKnetCommunity/Training#96]
and this way it can serve as many things

Will probably need some consistency renaming in JavaScript Code

**Comment by timmwille** [comment]
maybe also "Day Slot" or we find a complete other naming convention?

- Slot
- Break
- Unit
- Spacer
- Wildcard
- Placeholder
- or similar

**Comment by walthierer** [comment]
definitely not: 
Unit
Spacer
Wildcard
Placeholder

from my POV break is the most intuitv wording for it. nevertheless the wording can be changed in one minute so what ever works
